server:
  port: 8080
  display-name: MapAbc
  context-path: /utcsystem
  tomcat:
    max-threads: 1000

#线程池配置
threadPool:
  corePoolSize: 5
  maxPoolSize: 200
  queueCapacity: 5

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://44.104.93.92:3306/its_db_190506?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'&useSSL=false&useCursorFetch=true
    username: root
    password: mapabc
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置:
    filters: stat
    minIdle: 50
    maxActive: 200
    initialSize: 10
    # 等待获取连接的时间
    maxWait: 5000
    # 连接保持空闲而不被驱逐的最小时间
    minEvictableIdleTimeMillis: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 30000
    # 测试连接有效性
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    keepAlive: false
    # 指定获取连接时连接校验的sql查询语句
    validationQuery: SELECT 1
    # 启用ps
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    maxOpenPreparedStatements: -1
    # 记录被判定为异常的连接
    logAbandoned: true
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    host: 44.104.93.87
    port: 6379
    password: mapabc@2017
    pool:
      maxActive: 100
      maxWait: -1
      maxIdle: 10
      minIdle: 10
    timeout: 10000

# 信号优化
signalamp:
  # 供应商-厂家接口
  vendor:
    qs:
      # QS接口适配服务是否开启
      switch: true
      rootpath: http://192.168.205.210/scss.api
      username: mapabc
      password: mapabc2017
      login: /api/user/login
      getSignalList: /api/controllers
  # 基础信息
  basic:
    # 平均车长
    carLength: 7.0


