spring:
  profiles:
    active: dev

service:
  name: traffic-signal-utcsystem

mybatis:
  type-aliases-package: com.mapabc.signal.*.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.mapabc.signal.dao.MyBaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql